[workspace]

members = [
    "polybase",
    "indexer",
    "gateway",
    "solid",
    "schema",
    "indexer_db_adaptor",
    "indexer_rocksdb",
    "indexer_pg",
]

[profile.release]
debug-assertions = true
