# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: validator-keys
# data:
#   run.sh: |
#     #!/bin/sh
#     SET_INDEX=${HOSTNAME##*-}
#     echo "Starting initializing for pod $SET_INDEX"
#     mkdir -p /polybase/config/
#     cp /mnt/tendermint_files/genesis.json /polybase/config/genesis.json
#     cp /mnt/tendermint_files/node_key${SET_INDEX}.json /polybase/config/node_key.json
#     cp /mnt/tendermint_files/priv_validator_key${SET_INDEX}.json /polybase/config/priv_validator_key.json