{{- range .Values.deployments }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: 
  {{- if .labels }}
  {{- toYaml .labels | nindent 4}}
  {{- end }}
  {{- if .commonAnnotations }}
  annotations: {{- include "polybase.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: polybase
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels: 
        app: polybase 
      {{- if .podLabels }}
      {{- toYaml .podLabels | nindent 8 }}
      {{- end }}
      {{- if or .podAnnotations }}
      annotations:
        {{- if .podAnnotations }}
        {{- toYaml .podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector: {{- include "polybase.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "polybase.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          command: {{ .command }}
          {{- if .args }}
          args:  {{ .args }}
          {{- end }}
          image: {{ include "polybase.main_image" $ }}
          imagePullPolicy: {{ .imagePullPolicy | quote }}
          env:
            FOO: BAR
            {{- if .extraEnvVars }}
            {{- include "polybase.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 10 }}
            {{- end }}
          {{- if .customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            successThreshold: {{ .livenessProbe.successThreshold }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /v0/health
              port: 8080
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            successThreshold: {{ .readinessProbe.successThreshold }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .startupProbe.periodSeconds }}
            timeoutSeconds: {{ .startupProbe.timeoutSeconds }}
            successThreshold: {{ .startupProbe.successThreshold }}
            failureThreshold: {{ .startupProbe.failureThreshold }}
          {{- end }}
          ports:
            - name: public-api
              containerPort: {{ .containerPorts.public_api | default "8080" }}
              {{- if .hostNetwork }}
              hostPort: {{ .containerPorts.public_api }}
              {{- end }}
            - name: p2p
              containerPort: {{ .containerPorts.p2p | default "5001" }}
              {{- if .hostNetwork }}
              hostPort: {{ .containerPorts.p2p }}
              {{- end }}
          {{- if .resources }}
          resources: {{ toYaml .resources | nindent 12 }}
          {{- end }}
{{- end }}
