# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: genesis
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: genesis
#   data:
#   - secretKey: genesis.json
#     remoteRef:
#       key: testnet/genesis.json


# {{- range $i := until (.Values.replicaCount | int) }}
# ---

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: node-key-{{$i}}
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: node-key{{$i}}
#   data:
#   - secretKey: node_key{{$i}}.json
#     remoteRef:
#       key: testnet/node_key{{$i}}.json

# ---

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: priv-key{{$i}}
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: priv-validator-key{{$i}}
#   data:
#   - secretKey: priv_validator_key{{$i}}.json
#     remoteRef:
#       key: testnet/priv_validator_key{{$i}}.json

# {{- end }}