{{- range $i := until (.Values.replicaCount | int) }}
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-key-{{$i}}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-key-{{$i}}
  data:
  - secretKey: secret_key-{{$i}}
    remoteRef:
      key: {{ $.Values.env }}/secret_key_node_{{$i}}
      property: secret_key

{{- end }}