apiVersion: v1
kind: Service
metadata:
  name: {{ include "polybase.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "polybase.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "polybase.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "polybase.render" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "polybase.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: p2p
      port: 5001
      targetPort: 5001
    - name: public-api
      port: {{ .Values.service.ports.public_api }}
      targetPort: 8080
  selector: {{- include "polybase.matchLabels" . | nindent 4 }}