apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybase-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "polybase-ip"
    networking.gke.io/managed-certificates: "{{ $.Values.env }}-cert"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: lb-http-to-https
spec:
  rules:
  - http:
      paths:
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: polybase
            port:
              number: 8080