apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  domains:
    - {{ .Values.env }}.polybase.xyz
    {{ if .Values.additionalDomain -}} 
    - {{.Values.additionalDomain }}
     {{- end }}