[package]
name = "polybase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "4"
indexer = { path = "../indexer" }
gateway = { path = "../gateway" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "2.2", features = ["json"] }
hex = "0.4.3"
futures = "0.3.26"
sha3 = "0.10.6"
secp256k1 = { version = "0.26", features = ["recovery", "global-context"] }
