[package]
name = "rbmerkle"
version = "VERSION"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4.0"
winter-crypto = "0.4.2"

[[bench]]
name = "bench"
harness = false
