version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: polybase_postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - ../.env.postgres
    volumes:
      - devdb:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: polybase_pgadmin
    ports:
      - '${PGADMIN_PORT}:80'
    env_file:
      - ../.env.postgres
volumes:
  devdb:
