env: mainnet

image:
  registry: gcr.io
  repository: polybase-mainnet/polybase
  tag: latest
  digest: ""
  pullPolicy: Always

resources:
  limits:
    cpu: 3
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 300Mi

service:
  annotations:
    cloud.google.com/backend-config: '{"default": "polybase"}'
    cloud.google.com/neg: '{"ingress": true}'

peerList: "polybase-0.polybase-headless.polybase.svc.cluster.local:5001"

whitelist: "0xea448a816eba719df5155f1799d014d6ce74638fc5d42780597ad7e9df046a486ba295ed1c8364d284c416b350ba6b4e4db4966faf053e98cca6cab9fd6aa266"
