env: mainnet

image:
  registry: gcr.io
  repository: polybase-mainnet/polybase
  tag: latest
  digest: ""
  pullPolicy: Always

resources:
  limits:
    cpu: 3
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 300Mi

peerList: "polybase-0.polybase-headless.polybase.svc.cluster.local:5001"
