env: prenet

labels:
   kube-monkey/enabled: enabled
   kube-monkey/identifier: polybase
   kube-monkey/mtbf: "1"
   kube-monkey/kill-mode: "random-max-percent"
   kube-monkey/kill-value: "60"

podLabels:
   kube-monkey/enabled: enabled
   kube-monkey/identifier: polybase
   kube-monkey/mtbf: "1"
   kube-monkey/kill-mode: "random-max-percent"
   kube-monkey/kill-value: "60"

replicaCount: 3

image:
   registry: gcr.io
   repository: polybase-prenet/polybase
   tag: latest
   digest: ""
   pullPolicy: Always

resources:
   limits:
      cpu: 1
      memory: 1Gi
   requests:
      cpu: 200m
      memory: 300Mi

persistence:
   storageClass: ""
   size: 20Gi

extraEnvVars:
   - name: LOG_LEVEL
     value: "DEBUG"
   - name: RESTRICT_NAMESPACES
     value: "true"
   - name: PEERS
     value: "12D3KooWGwYHQGP9xJ8uxrmfhZMubfAsWPrTByGgq2N8hH2atMJZ,12D3KooWKLvUcUc4h3BEKGHKMz2kxfS7Xpps2kEfaQzpchGmMgSy,12D3KooWLYByKfin35Dh37YJf8HwQfyrL2beJW67712y9kChgbja"
   - name: DIAL_ADDR
     value: "/dns/polybase-rust-0.polybase-rust-headless.polybase.svc.cluster.local/tcp/5001,/dns/polybase-rust-1.polybase-rust-headless.polybase.svc.cluster.local/tcp/5001,/dns/polybase-rust-2.polybase-rust-headless.polybase.svc.cluster.local/tcp/5001"
   - name: MIGRATION_BATCH_SIZE
     value: "2000"
