env: prenet

image:
   registry: gcr.io
   repository: polybase-prenet/polybase
   tag: latest
   digest: ""
   pullPolicy: Always

resources:
   limits:
      cpu: 1
      memory: 1Gi
   requests:
      cpu: 200m
      memory: 300Mi

persistence:
   storageClass: ""
   size: 20Gi

extraEnvVars:
   - name: PEERS
     value: "12D3KooWGwYHQGP9xJ8uxrmfhZMubfAsWPrTByGgq2N8hH2atMJZ,12D3KooWKLvUcUc4h3BEKGHKMz2kxfS7Xpps2kEfaQzpchGmMgSy,12D3KooWLYByKfin35Dh37YJf8HwQfyrL2beJW67712y9kChgbja"
