env: prenet

image:
   registry: gcr.io
   repository: polybase-prenet/polybase
   tag: latest
   digest: ""
   pullPolicy: Always

peerList: "polybase-rust-0.polybase-rust-headless.polybase.svc.cluster.local:5001"

resources:
   limits:
      cpu: 1
      memory: 1Gi
   requests:
      cpu: 200m
      memory: 300Mi

persistence:
   storageClass: ""
   size: 20Gi

extraEnvVars:
   - name: WHITELIST
     value: "0xea448a816eba719df5155f1799d014d6ce74638fc5d42780597ad7e9df046a486ba295ed1c8364d284c416b350ba6b4e4db4966faf053e98cca6cab9fd6aa266"
   - name: TEST
     value: "test"
