apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-polybase-full-nodes-0-restore
spec:
  dataSource:
    name: validator-node-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
