env: testnet

image:
  registry: gcr.io
  repository: polybase-testnet/polybase
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 3
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 300Mi

additionalDomain: testnet.spacetime.xyz

extraEnvVars:
  - name: PEERS
    value: "12D3KooWSZxfWBu726XtsGumTFtmqFTTenud1HempLgHx5kSvBaM,12D3KooWNSEqaQB4ZHFrdw4A1efz3G5aTxzfRPXPjrT5z2yfGaTs,12D3KooWPBFaDpnqiPRTQZqvf1W41fcszS27qPhpkL757Z2XSkcz"
  - name: SNAPSHOT_CHUNK_SIZE
    value: "8388608"
