env: testnet

image:
  registry: gcr.io
  repository: polybase-testnet/polybase
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 3
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 300Mi

peerList: "polybase-rust-0.polybase-rust-headless.polybase.svc.cluster.local:5001"

additionalDomain: testnet.spacetime.xyz
