env: testnet

image:
  registry: gcr.io
  repository: polybase-testnet/polybase
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent

peerList: "polybase-rust-0.polybase-headless.polybase.svc.cluster.local:5001"

resources:
  limits:
     cpu: 1
     memory: 1Gi
  requests:
     cpu: 200m
     memory: 300Mi

additionalDomain: testnet.spacetime.xyz
