name: Clippy check

on:
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "helm/**"

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
