name: Mainnet deploy

on:
  push:
    branches:
    - "mainnet-helm"

env:
  GCLOUD_PROJECT: polybase-mainnet
  GKE_CLUSTER: mainnet
  GKE_ZONE: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    # Log in to the image registry
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.MAINNET_GCR_KEY }}

    # Build the Docker image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          gcr.io/polybase-mainnet/polybase
        flavor: latest=true
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha
          type=ref,event=tag

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        build-arg: |
          BUILDKIT_INLINE_CACHE=1
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    #Get tag
    - name: Set outputs
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.tag }}
