name: Prenet deploy

on:
  push:
    branches:
      - main

env:
  GCLOUD_PROJECT: polybase-prenet
  GKE_CLUSTER: prenet
  GKE_ZONE: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Log in to the image registry
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PRENET_GCR_KEY }}

      # Build the Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: v0.9.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            gcr.io/polybase-prenet/polybase
          flavor: latest=true
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Auth GKE
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.PRENET_GCR_KEY }}

      - name: Get GKE Credentials
        uses: "google-github-actions/get-gke-credentials@v0"
        with:
          project_id: ${{ env.GCLOUD_PROJECT }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Set up helm
      - name: Set up Helm
        run: |-
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      #Get sha
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

  #     - name: Deploy
  #       run: |-
  #         cd ./helm/
  #         helm upgrade --install --set image.tag=sha-${{ steps.vars.outputs.sha_short }} polybase . -f prenet-values.yaml -n polybase
