on: [push]

name: Test

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest-16-cores
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler

      - name: Run unit tests
        run: cargo test

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest-16-cores
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: polybase-rust

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: polybase-ts
          repository: polybase/polybase-ts
          token: ${{ secrets.ADMIN_TOKEN }}

      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: ./polybase-ts/yarn.lock

      - name: Build server
        working-directory: polybase-rust
        run: cargo build --bin polybase

      - name: Run server
        working-directory: polybase-rust
        run: cargo run --bin polybase &

      - name: Install deps
        working-directory: polybase-ts
        run: yarn install && yarn build
        
      - name: Run E2E tests
        working-directory: polybase-ts/packages/client
        run: yarn test:e2e

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
      
      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
