on:
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "helm/**"

name: Test

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest-16-cores
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Depot
        uses: depot/setup-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build unit test
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          build-args: |
            RELEASE=0
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: unit-tests
          tags: polybase-unit-tests

      - name: Run unit tests
        run: |
          docker run polybase-unit-tests

      - name: Build e2e tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          build-args: |
            RELEASE=0
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: e2e-polybase-ts-tests
          tags: polybase-e2e-polybase-ts-tests

      - name: Run e2e tests
        run: |
          docker run polybase-e2e-polybase-ts-tests
