on:
  push:

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build in Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        build-args: |
          RELEASE=0
        outputs: type=docker
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: unit-tests
        tags: polybase-unit-tests
    - name: Run unit tests
      run: |
        docker run polybase-unit-tests
  test-api:
    name: E2E API tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build in Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        build-args: |
          RELEASE=0
        outputs: type=docker
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: e2e-api-tests
        tags: polybase-e2e-api-tests
    - name: Run e2e tests
      run: |
        docker run polybase-e2e-api-tests
  test-e2e:
    name: E2E @polybase/client tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build in Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        build-args: |
          RELEASE=0
        outputs: type=docker
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: e2e-client-tests
        tags: polybase-e2e-client-tests
    - name: Run e2e tests
      run: |
        docker run polybase-e2e-client-tests
