on:
  push:

name: Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-16-cores
    needs: "test"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build in Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          build-args: |
            RELEASE=0
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
